apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gqol
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0011-tenant/tkrw-pr712-0075-0011-app/devfile-sample-gqol@sha256:bad6f89756a80fef2f46b799d1443f614d5a023c4c9c1614d3b79bd35453cf50
        name: my-nodejs
        resources: {}
status: {}
